### ISSUE TITLE
AttributeError: 'str' object has no attribute 'to'

### ISSUE THREAD

**Issue by vincent507cpu** [THUDM/LongBench#53]
```
Traceback (most recent call last):
  File "/home/./miniconda3/envs/longbench/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/./miniconda3/envs/longbench/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/./GitHub/LongBench-main/pred.py", line 66, in get_pred
    input = prompt.to(device)
            ^^^^^^^^^
AttributeError: 'str' object has no attribute 'to
```

**Comment by bys0318** [comment]
Thanks for pointing it out! We have corrected the code.
