### ISSUE TITLE
RuntimeError when running pred.py for Vicuna-v1.5-7B-16k

### ISSUE THREAD

**Issue by fuqichen1998** [THUDM/LongBench#58]
I got this error when running pred.py for Vicuna-v1.5-7B-16k. While the script continues run after this error, can you share why this error pops up and how to fix it?

```
Process Process-1:
Traceback (most recent call last):
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1176, in forward
    outputs = self.model(
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 993, in forward
    causal_mask = self._update_causal_mask(attention_mask, inputs_embeds)
  File "/miniconda/envs/myenv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1079, in _update_causal_mask
    padding_mask = causal_mask[..., :mask_length].eq(0.0) * attention_mask[:, None, None, :].eq(0.0)
RuntimeError: The size of tensor a (8192) must match the size of tensor b (15539) at non-singleton dimension 3
```

**Comment by bys0318** [comment]
Hi! I can successfully run `pred.py` for Vicuna-v1.5-7B-16k. I'm using `transformers==4.33.0`.

**Comment by fuqichen1998** [comment]
`transformers==4.33.0` works for me, thanks!
