### ISSUE TITLE
安装完longbench后，运行报错

### ISSUE THREAD

**Issue by fxnie** [THUDM/LongBench#86]
(longbench) root@pod-1317538633040015360:/workspace/mnt/cm-nfx/LongBench# CUDA_VISIBLE_DEVICES=0 python pred.py --model chatglm3-6b-32k
The repository for THUDM/LongBench contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/THUDM/LongBench.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
Traceback (most recent call last):
  File "/workspace/mnt/cm-nfx/LongBench/pred.py", line 166, in <module>
    data = load_dataset('THUDM/LongBench', dataset, split='test')
  File "/opt/conda/envs/longbench/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/envs/longbench/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
TypeError: 'NoneType' object is not callable

**Comment by zZzZ9zZ9** [comment]
I also encountered this problem, did you solve it? Thank you

**Comment by fxnie** [comment]
@zZzZ9zZ9 Maybe it is network problem ，Is your environment connected to the internet.
你可以尝试把数据集下载到本地进行加载

**Comment by zZzZ9zZ9** [comment]
网络是正确连接的，下载其他数据集也没有问题。在几台服务器中会有这个报错，另一些服务器没有问题，最后解决方法是直接把.cache中的整个huggingface文件夹copy过来）Thanks for your reply！
